const units: [string, Intl.RelativeTimeFormatUnit, number][] = [
  ['y', "year",   365 * 24 * 60 * 60 * 1000],
  ['m', "month",  30  * 24 * 60 * 60 * 1000],
  ['w', "week",    7  * 24 * 60 * 60 * 1000],
  ['d', "day",     24 * 60 * 60 * 1000],
  ['h', "hour",    60 * 60 * 1000],
  ['i', "minute",  60 * 1000],
  ['s', "second",  1000]
];

const unitsCorrespondence: {[key: string]: string} = {
  'years': 'y',
  'year': 'y',
  'YEARS': 'y',
  'YEAR': 'y',
  'Years': 'y',
  'Year': 'y',
  'YYYY': 'y',
  'YY': 'y',
  'yyyy': 'y',
  'yy': 'y',
  'months': 'm',
  'month': 'm',
  'Months': 'm',
  'Month': 'm',
  'MONTHS': 'm',
  'MONTH': 'm',
  'MMMM': 'm',
  'MMM': 'm',
  'MM': 'm',
  'weekday': 'e',
  'WEEKDAY': 'e',
  'ee': 'e',
  'EE': 'e',
  'ddd': 'e',
  'days': 'd',
  'day': 'd',
  'Days': 'd',
  'Day': 'd',
  'DAYS': 'd',
  'DAY': 'd',
  'DD': 'd',
  'dd': 'd',
  'hours': 'h',
  'hour': 'h',
  'Hours': 'h',
  'Hour': 'h',
  'HOURS': 'h',
  'HOUR': 'h',
  'HH': 'h',
  'hr': 'h',
  'hh': 'h',
  'minutes': 'i',
  'minute': 'i',
  'Minutes': 'i',
  'Minute': 'i',
  'MINUTES': 'i',
  'MINUTE': 'i',
  'II': 'i',
  'ii': 'i',
  'mn': 'i',
  'mm': 'i',
  'min': 'i',
  'SS': 's',
  'ss': 's',
  'seconds': 's',
  'second': 's',
  'Seconds': 's',
  'Second': 's',
  'SECONDS': 's',
  'SECOND': 's',
  'sec': 's',
  'WW': 'w',
  'Y': 'y',
  'y': 'y',
  'M': 'm',
  'm': 'm',
  'e': 'e',
  'E': 'e',
  'D': 'd',
  'd': 'd',
  'H': 'h',
  'h': 'h',
  'n': 'i',
  'i': 'i',
  's': 's',
  'S': 's',
  'W': 'w',
  'w': 'w'
};

const unitsMap: {[key: string]: string} = {
  'y': 'Year',
  'm': 'Month',
  'd': 'Date',
  'w': 'Week',
  'h': 'Hours',
  'i': 'Minutes',
  's': 'Seconds'
};

const formatsMap: {[key: string]: string} = {
  'y': 'YYYY',
  'm': 'MM',
  'd': 'DD',
  'e': 'EE',
  'w': 'WW',
  'h': 'HH',
  'i': 'II',
  's': 'SS'
};


export {units, unitsCorrespondence, unitsMap, formatsMap};